# This is a basic workflow to help you get started with Actions

name: Discord 알리미

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest #깃헙 원격 서버에서 돌아가는 것이기 때문에 우분투 운영체제에서 돌아가도록 하겠다고 설정한 것. 이걸 가장 많이 쓴대

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 #서버에서는 레포에 있는 걸 클론 받아서 돌림. 클론 받고 마스터 브랜치에서 확인하는 작업을 해줌. 항상 놔두기

      - name: 멋사 안녕
        run: echo "멋사 안녕"

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'

